import { Schema, model } from 'mongoose';

const AgentSchema = new Schema({
    adminId: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    agentName: {
        type: String,
        required: true
    },
    language: {
        type: String,
        default: 'hi' // Default to Hindi
    },
    knowledgeBase: {
        type: String,
        required: true
    },
    // These are generated by AI based on the knowledgeBase
    systemPrompt: {
        type: String
    },
    greeting: {
        type: String
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

export default model('Agent', AgentSchema);